#!/usr/bin/env bash
# credits to RavenHeart and Kevin Ferranti https://stackoverflow.com/q/54637049

wsNext=$(( $( i3-msg -t get_workspaces | jq '.[] | select(.focused).num' ) + $1))
i3-msg move container to workspace number $wsNext
i3-msg workspace number $wsNext
